# 04 · Top-1 Recommendation Accuracy

**Purpose:** Every other metric in this project (MAPE, Spearman ρ) measures point-prediction
accuracy. None of them answer the question a user of the recommender actually cares about:
*if you ask the system for a GPU recommendation, does it pick the one that's actually best?*

This notebook builds that benchmark directly from real, already-collected data — no new
benchmarking, no hand-curated ground truth. For every (model, accuracy tier, scenario)
combination where at least two in-scope GPUs have real measured throughput, and for a range
of realistic budget / minimum-throughput constraints, we compare:

- **Ground truth top pick** — ranked using the *actual measured* throughput for each GPU.
- **Predicted top pick** — ranked using *out-of-fold* predicted throughput (each GPU's
  prediction comes from a model trained without that GPU's data — the exact same LOGO-CV
  protocol used everywhere else in this project). Using the production model instead would
  be self-grading: it was trained on every in-scope GPU, so testing it on them would measure
  memorization, not the generalization claim this project is actually making.

Ranking logic (Pareto frontier + cost-efficiency ordering) is imported directly from
`src/recommend/recommender.py` — not reimplemented — so this measures the real recommender
algorithm, just fed out-of-fold predictions instead of live single-model inference.

Ground truth for MI300X uses **official MLPerf submissions only**, excluding the self-run
AMD Dev Cloud calibration rows — consistent with how those rows are scored everywhere else
in this project (see `03_model_training.ipynb`), since they measure a different, untuned
serving-stack regime and would understate MI300X's true achievable throughput.

In [1]:
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

sys.path.append(str(Path("..").resolve()))

from src.features.build_features import build_training_df, MODEL_PARAMS, TIER_TO_PRECISION, BYTES_PER_PARAM
from src.data.gpu_spec_db import load_specs
from src.recommend.recommender import _pareto_frontier, _load_pricing

import logging
logging.getLogger("src").setLevel(logging.WARNING)

## §1 · Load data

Same corpus-construction path as `03_model_training.ipynb`: rebuild from raw MLPerf data,
then fold in the self-run MI300X calibration rows.

In [2]:
INPUT_PATH = Path("..") / "data" / "processed" / "mlperf_raw.parquet"
CALIBRATION_CSV = Path("..") / "benchmarks" / "mi300x_calibration_results.csv"

raw = pd.read_parquet(INPUT_PATH)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    feat = build_training_df(raw)

    if CALIBRATION_CSV.exists():
        from benchmarks.merge_calibration_rows import _build_raw_df
        cal_raw = _build_raw_df(CALIBRATION_CSV)
        cal_feat = build_training_df(cal_raw)
        pk_cols = ["submitter", "system_name", "benchmark", "scenario", "round", "division"]
        is_dupe = cal_feat[pk_cols].apply(tuple, axis=1).isin(feat[pk_cols].apply(tuple, axis=1))
        feat = pd.concat([feat, cal_feat[~is_dupe]], ignore_index=True)

print(f"Total rows: {len(feat):,}")

45 rows: vram_gb (parser) != gpu_vram_gb (spec DB). Some submitters report total system VRAM. Use gpu_vram_gb for the memory-fit constraint.

  vram conflict: gpu='NVIDIA L40S'  num_gpus=2  reported=64.0  spec=48.0

  vram conflict: gpu='AMD Instinct MI325X 256GB HBM3E'  num_gpus=8  reported=2048.0  spec=256.0

  vram conflict: gpu='NVIDIA GB200'  num_gpus=4  reported=186.0  spec=384.0

  vram conflict: gpu='NVIDIA GB200'  num_gpus=72  reported=186.0  spec=384.0

  vram conflict: gpu='NVIDIA GB300'  num_gpus=72  reported=288.0  spec=384.0

Dropping 110 rows with missing GPU specs (cannot compute roofline)

Dropping 1 rows with efficiency_ratio outside (0, 1.2] (sample values: [nan]) — outlier-rejection rule; likely a spec-DB or parse error, not valid training signal.

13:55:22  INFO     Loaded 24 successful calibration rows from ../benchmarks/mi300x_calibration_results.csv

13:55:22  INFO     Constructed 24 raw rows ready for feature engineering

Total rows: 1,136

In [3]:
THROUGHPUT_COL = "throughput_tok_per_sec_per_gpu"
TARGET = "efficiency_ratio"

BASE_FEATURE_COLS = [
    "gpu_hbm_bandwidth_tbps", "gpu_vram_gb", "peak_tflops_selected",
    "compute_ceiling_tok_per_sec", "bandwidth_ceiling_tok_per_sec",
    "model_total_params_b", "model_compute_params_b", "model_size_gb",
    "model_to_vram_ratio", "bytes_per_param",
    "nvidia_arch_gen", "amd_arch_gen", "vendor_is_amd",
]
# mlperf_round_num must come AFTER the encoded categoricals (CONTEXT_COLS is
# appended last below), matching predictor.py's FEATURE_COLS order exactly —
# XGBoost's colsample_bytree does positional random feature subsampling, so a
# reordered column set trains a different concrete model than production
# even with the same random_state.
CONTEXT_COLS = ["mlperf_round_num"]
META_COLS = ["canonical_gpu_id", "gpu_vendor", "roofline_tput", THROUGHPUT_COL,
             "gpu_in_model_scope", "submitter"]

df = feat[BASE_FEATURE_COLS + CONTEXT_COLS + [TARGET] + META_COLS +
          ["scenario", "benchmark_accuracy_tier", "framework_family", "is_base_tier",
           "benchmark_base"]].copy()

df["scenario_offline"] = (df["scenario"] == "Offline").astype(int)
_fw_dummies = pd.get_dummies(df["framework_family"], prefix="fw", dtype=int)
for col in ["fw_tensorrt", "fw_vllm", "fw_rocm_other"]:
    df[col] = _fw_dummies.get(col, 0)
df["is_cdna4"] = (df["amd_arch_gen"] == 2).astype(int)
df["is_self_run"] = df["submitter"] == "vxa8502"

ENCODED_COLS = ["scenario_offline", "is_base_tier", "fw_tensorrt", "fw_vllm",
                "fw_rocm_other", "is_cdna4"]
FEATURE_COLS = BASE_FEATURE_COLS + ENCODED_COLS + CONTEXT_COLS

target_ok = df[TARGET].notna() & np.isfinite(df[TARGET])
df = df[target_ok].reset_index(drop=True)
print(f"Training rows: {len(df):,}  Features: {len(FEATURE_COLS)}")

Training rows: 1,136  Features: 20

## §2 · LOGO-CV out-of-fold predictions

Identical model config to `03_model_training.ipynb` §3-4. For each in-scope GPU, train on
every other GPU and predict on the held-out GPU's own rows — the resulting predictions are
never influenced by that GPU's own data, so comparing them to ground truth is a fair
generalization test.

In [4]:
MODEL_PARAMS_XGB = dict(
    n_estimators=500, max_depth=5, learning_rate=0.03, subsample=0.8,
    colsample_bytree=0.8, min_child_weight=5, tree_method="hist",
    random_state=42, early_stopping_rounds=30, eval_metric="mape",
)

IN_SCOPE_TRAINED_GPUS = ["h100_sxm", "h200_sxm", "mi300x", "mi325x", "mi355x"]

oof_rows = []
for gpu_id in IN_SCOPE_TRAINED_GPUS:
    is_test = df["canonical_gpu_id"] == gpu_id
    is_train = ~is_test

    X_train, y_train = df.loc[is_train, FEATURE_COLS], df.loc[is_train, TARGET]
    X_test, y_test = df.loc[is_test, FEATURE_COLS], df.loc[is_test, TARGET]

    model = xgb.XGBRegressor(**MODEL_PARAMS_XGB)
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

    pred_eff = model.predict(X_test)
    roofline = df.loc[is_test, "roofline_tput"].values
    pred_tput = pred_eff * roofline

    sub = df.loc[is_test, ["canonical_gpu_id", "benchmark_base", "benchmark_accuracy_tier",
                            "scenario", "is_self_run", THROUGHPUT_COL]].copy()
    sub["pred_tput"] = pred_tput
    oof_rows.append(sub)
    print(f"  {gpu_id:<12}  n={is_test.sum():>4}  trained on {is_train.sum():,} rows")

oof_df = pd.concat(oof_rows, ignore_index=True)
print(f"\nOut-of-fold predictions: {len(oof_df):,} rows")

  h100_sxm      n= 178  trained on 958 rows

  h200_sxm      n= 283  trained on 853 rows

  mi300x        n=  80  trained on 1,056 rows
  mi325x        n=  82  trained on 1,054 rows

  mi355x        n=  50  trained on 1,086 rows

Out-of-fold predictions: 673 rows

## §3 · Workload combinations with real multi-GPU coverage

Ground truth is built entirely from official MLPerf submissions (self-run calibration rows
excluded here — see notebook purpose above). Only combinations where ≥2 in-scope GPUs
actually have official measured data are usable, since "which GPU is best" is undefined
with fewer than two candidates.

In [5]:
official = oof_df[~oof_df["is_self_run"]]

combo_gpus = (
    official.groupby(["benchmark_base", "benchmark_accuracy_tier", "scenario"])["canonical_gpu_id"]
    .agg(lambda s: sorted(set(s)))
    .reset_index(name="gpus")
)
combo_gpus["n_gpus"] = combo_gpus["gpus"].apply(len)
combos = combo_gpus[combo_gpus["n_gpus"] >= 2].reset_index(drop=True)
print(f"Usable workload combinations: {len(combos)}")
display(combos)

Usable workload combinations: 12

,benchmark_base,benchmark_accuracy_tier,scenario,gpus,n_gpus
0,gptj,99,Offline,"[h100_sxm, h200_sxm]",2
1,gptj,99,Server,"[h100_sxm, h200_sxm]",2
2,gptj,99.9,Offline,"[h100_sxm, h200_sxm]",2
3,gptj,99.9,Server,"[h100_sxm, h200_sxm]",2
4,llama2-70b,99,Interactive,"[h200_sxm, mi300x, mi325x, mi355x]",4
5,llama2-70b,99,Offline,"[h100_sxm, h200_sxm, mi300x, mi325x, mi355x]",5
6,llama2-70b,99,Server,"[h100_sxm, h200_sxm, mi300x, mi325x, mi355x]",5
7,llama2-70b,99.9,Interactive,"[h200_sxm, mi300x, mi325x, mi355x]",4
8,llama2-70b,99.9,Offline,"[h100_sxm, h200_sxm, mi300x, mi325x, mi355x]",5
9,llama2-70b,99.9,Server,"[h100_sxm, h200_sxm, mi300x, mi325x, mi355x]",5
10,mixtral-8x7b,base,Offline,"[h100_sxm, h200_sxm, mi300x, mi325x]",4
11,mixtral-8x7b,base,Server,"[h100_sxm, h200_sxm, mi300x, mi325x]",4

## §4 · Per-GPU representative values

For each (combination, GPU) pair, take the mean actual and mean out-of-fold predicted
throughput across official rows — mirrors how every other aggregate metric in this project
handles the (rare) case of multiple submitters for the same configuration.

`watts` (GPU TDP) is looked up per GPU and passed into the Pareto ranking exactly as
`recommender.py` does (the `(throughput, price_per_gpu_hr, watts)` objective vector —
previously `vram_headroom` stood in for `watts` here and in
`recommender.py` alike). `vram_headroom` is still computed for display/reference, but is no
longer read by `_pareto_frontier()`. Unlike `recommender.py`, this notebook does **not**
separately hard-exclude a candidate for not fitting in VRAM: every candidate here comes from
a real MLPerf or calibration submission for that exact (model, tier) pair, which implies the
configuration already fit on that GPU. A live user query has no such guarantee, which is
why `recommender.py` checks it explicitly and this benchmark can skip it.

In [6]:
specs = {s["id"]: s for s in load_specs()}
pricing = _load_pricing(Path("..") / "data" / "pricing.yaml")

def model_size_gb(model_name: str, tier: str, vendor: str) -> float:
    total_b, _ = MODEL_PARAMS[model_name]
    precision = TIER_TO_PRECISION[tier]
    if vendor == "amd" and tier == "99.9":
        precision = "fp8"
    return total_b * BYTES_PER_PARAM[precision]

# Single groupby over `official` instead of re-scanning the whole frame once per
# combo: `combos` is already derived from official's own (benchmark_base,
# benchmark_accuracy_tier, scenario) groups, so canonical_gpu_id is implicitly
# restricted to that combo's `gpus` set — no separate isin() filter is needed,
# and this avoids the O(combos x len(official)) mask scans the loop version did.
combo_keys = combos[["benchmark_base", "benchmark_accuracy_tier", "scenario"]]
cand_df = (
    official.groupby(["benchmark_base", "benchmark_accuracy_tier", "scenario", "canonical_gpu_id"])
    .agg(actual_tput=(THROUGHPUT_COL, "mean"), pred_tput=("pred_tput", "mean"))
    .reset_index()
    .merge(combo_keys, on=["benchmark_base", "benchmark_accuracy_tier", "scenario"])
    .rename(columns={"canonical_gpu_id": "gpu_id"})
)

cand_df["vendor"] = cand_df["gpu_id"].map(lambda g: specs[g]["vendor"])
cand_df["price_per_gpu_hr"] = cand_df["gpu_id"].map(pricing)
cand_df["watts"] = cand_df["gpu_id"].map(lambda g: specs[g]["tdp_w"])
_model_size = cand_df.apply(
    lambda r: model_size_gb(r["benchmark_base"], r["benchmark_accuracy_tier"], r["vendor"]), axis=1
)
_vram_gb = cand_df["gpu_id"].map(lambda g: specs[g]["vram_gb"])
cand_df["vram_headroom"] = (1.0 - _model_size / _vram_gb).clip(lower=0.0)

cand_df = cand_df[["benchmark_base", "benchmark_accuracy_tier", "scenario", "gpu_id", "vendor",
                    "actual_tput", "pred_tput", "price_per_gpu_hr", "watts", "vram_headroom"]]
print(f"Candidate (combo, GPU) rows: {len(cand_df)}")

Candidate (combo, GPU) rows: 44

## §5 · Scenario construction (budget + minimum-throughput constraints)

For each workload combination, generate one "unconstrained" scenario plus a budget-tier
scenario at every real candidate price point below the maximum (each one excludes a
progressively more expensive subset — using each candidate's actual price, not arbitrary
round numbers), plus a minimum-throughput scenario at the median *actual* throughput among
candidates (excludes the below-median half). Both constraint types are ones the recommender
actually supports (`budget_per_gpu_hr`, `min_throughput_tok_per_sec`); nothing here is a
constraint the deployed system can't enforce.

A scenario is only kept if it leaves ≥2 survivors under **both** the predicted and the
ground-truth view — otherwise there's no ranking decision to evaluate.

In [7]:
def rank_top1(rows: list[dict], tput_key: str) -> str | None:
    """Apply the exact recommender Pareto+ranking logic; return the top gpu_id or None."""
    cands = [{
        "gpu_id": r["gpu_id"],
        "throughput": r[tput_key],
        "price_per_gpu_hr": r["price_per_gpu_hr"],
        "watts": r["watts"],
        # cost_efficiency is still read by _pareto_frontier's default
        # ranking_objective ("tokens_per_dollar") — it's no longer a
        # dominance objective but the post-split sort
        # still needs it.
        "cost_efficiency": r[tput_key] / r["price_per_gpu_hr"] if r["price_per_gpu_hr"] else None,
    } for r in rows]
    frontier, _ = _pareto_frontier(cands)
    return frontier[0]["gpu_id"] if frontier else None

scenarios = []
for (bm, tier, scen), grp in cand_df.groupby(["benchmark_base", "benchmark_accuracy_tier", "scenario"]):
    rows = grp.to_dict("records")

    def eval_scenario(label, budget, min_tput):
        # Budget is a real, objective constraint (same for both views).
        # min_tput is applied separately below because it depends on which
        # throughput source (predicted vs actual) is being evaluated.
        survivors = [r for r in rows if budget is None or r["price_per_gpu_hr"] <= budget]
        if len(survivors) < 2:
            return
        pred_survivors = [r for r in survivors if min_tput is None or r["pred_tput"] >= min_tput]
        actual_survivors = [r for r in survivors if min_tput is None or r["actual_tput"] >= min_tput]
        if len(pred_survivors) < 1 or len(actual_survivors) < 1:
            return
        pred_top1 = rank_top1(pred_survivors, "pred_tput")
        actual_top1 = rank_top1(actual_survivors, "actual_tput")
        scenarios.append({
            "benchmark_base": bm, "accuracy_tier": tier, "scenario": scen,
            "constraint": label, "n_candidates": len(rows),
            "predicted_top1": pred_top1, "actual_top1": actual_top1,
            "match": pred_top1 == actual_top1,
        })

    eval_scenario("unconstrained", None, None)

    prices = sorted({r["price_per_gpu_hr"] for r in rows})
    for cap in prices[:-1]:
        eval_scenario(f"budget<=${cap:.2f}/hr", cap, None)

    if len(rows) >= 2:
        median_actual = float(np.median([r["actual_tput"] for r in rows]))
        eval_scenario(f"min_tput>={median_actual:.0f} tok/s", None, median_actual)

scenario_df = pd.DataFrame(scenarios)
print(f"Total scenarios generated: {len(scenario_df)}")

Total scenarios generated: 42

## §6 · Results

In [8]:
display(scenario_df[["benchmark_base", "accuracy_tier", "scenario", "constraint",
                     "n_candidates", "predicted_top1", "actual_top1", "match"]])

accuracy = scenario_df["match"].mean()
n = len(scenario_df)
n_correct = int(scenario_df["match"].sum())

print(f"\nTop-1 recommendation accuracy: {n_correct}/{n} = {accuracy:.1%}")
print(f"Target (>= 70%): {'PASS' if accuracy >= 0.70 else 'FAIL'}")

print("\nBy workload:")
by_workload = scenario_df.groupby(["benchmark_base", "accuracy_tier", "scenario"])["match"].agg(["mean", "count"])
print(by_workload.round(3).to_string())

mismatches = scenario_df[~scenario_df["match"]]
if len(mismatches):
    print(f"\nMismatches ({len(mismatches)}):")
    print(mismatches[["benchmark_base", "accuracy_tier", "scenario", "constraint",
                       "predicted_top1", "actual_top1"]].to_string(index=False))

,benchmark_base,accuracy_tier,scenario,constraint,n_candidates,predicted_top1,actual_top1,match
0,gptj,99,Offline,unconstrained,2,h100_sxm,h100_sxm,True
1,gptj,99,Offline,min_tput>=4724 tok/s,2,h100_sxm,h200_sxm,False
2,gptj,99,Server,unconstrained,2,h100_sxm,h100_sxm,True
3,gptj,99,Server,min_tput>=4699 tok/s,2,h100_sxm,h200_sxm,False
4,gptj,99.9,Offline,unconstrained,2,h100_sxm,h100_sxm,True
5,gptj,99.9,Server,unconstrained,2,h100_sxm,h100_sxm,True
6,llama2-70b,99,Interactive,unconstrained,4,mi355x,mi355x,True
7,llama2-70b,99,Interactive,budget<=$2.50/hr,4,mi300x,mi325x,False
8,llama2-70b,99,Interactive,budget<=$3.99/hr,4,mi300x,mi325x,False
9,llama2-70b,99,Interactive,min_tput>=2423 tok/s,4,mi355x,mi355x,True
10,llama2-70b,99,Offline,unconstrained,5,mi355x,mi355x,True
11,llama2-70b,99,Offline,budget<=$2.49/hr,5,mi300x,mi300x,True
12,llama2-70b,99,Offline,budget<=$2.50/hr,5,mi300x,mi325x,False
13,llama2-70b,99,Offline,budget<=$3.99/hr,5,mi300x,mi325x,False
14,llama2-70b,99,Offline,min_tput>=4139 tok/s,5,mi355x,mi355x,True
15,llama2-70b,99,Server,unconstrained,5,mi355x,mi355x,True
16,llama2-70b,99,Server,budget<=$2.49/hr,5,mi300x,mi300x,True
17,llama2-70b,99,Server,budget<=$2.50/hr,5,mi300x,mi325x,False
18,llama2-70b,99,Server,budget<=$3.99/hr,5,mi300x,mi325x,False
19,llama2-70b,99,Server,min_tput>=3870 tok/s,5,mi355x,mi355x,True
20,llama2-70b,99.9,Interactive,unconstrained,4,mi355x,mi355x,True
21,llama2-70b,99.9,Interactive,budget<=$2.50/hr,4,mi300x,mi325x,False
22,llama2-70b,99.9,Interactive,budget<=$3.99/hr,4,mi300x,mi325x,False
23,llama2-70b,99.9,Interactive,min_tput>=2423 tok/s,4,mi355x,mi355x,True
24,llama2-70b,99.9,Offline,unconstrained,5,mi355x,mi355x,True
25,llama2-70b,99.9,Offline,budget<=$2.49/hr,5,mi300x,mi300x,True
26,llama2-70b,99.9,Offline,budget<=$2.50/hr,5,mi300x,mi325x,False
27,llama2-70b,99.9,Offline,budget<=$3.99/hr,5,mi300x,mi325x,False
28,llama2-70b,99.9,Offline,min_tput>=4139 tok/s,5,mi355x,mi355x,True
29,llama2-70b,99.9,Server,unconstrained,5,mi355x,mi355x,True
30,llama2-70b,99.9,Server,budget<=$2.49/hr,5,mi300x,mi300x,True
31,llama2-70b,99.9,Server,budget<=$2.50/hr,5,mi300x,mi325x,False
32,llama2-70b,99.9,Server,budget<=$3.99/hr,5,mi300x,mi325x,False
33,llama2-70b,99.9,Server,min_tput>=3870 tok/s,5,mi355x,mi355x,True
34,mixtral-8x7b,base,Offline,unconstrained,4,mi300x,mi325x,False
35,mixtral-8x7b,base,Offline,budget<=$2.49/hr,4,mi300x,mi300x,True
36,mixtral-8x7b,base,Offline,budget<=$2.50/hr,4,mi300x,mi325x,False
37,mixtral-8x7b,base,Offline,min_tput>=7158 tok/s,4,mi300x,mi325x,False
38,mixtral-8x7b,base,Server,unconstrained,4,mi300x,mi300x,True
39,mixtral-8x7b,base,Server,budget<=$2.49/hr,4,mi300x,mi300x,True
40,mixtral-8x7b,base,Server,budget<=$2.50/hr,4,mi300x,mi300x,True
41,mixtral-8x7b,base,Server,min_tput>=6807 tok/s,4,mi300x,mi325x,False

Top-1 recommendation accuracy: 24/42 = 57.1%
Target (>= 70%): FAIL

By workload:
                                          mean  count
benchmark_base accuracy_tier scenario
gptj           99            Offline      0.50      2
                             Server       0.50      2
               99.9          Offline      1.00      1
                             Server       1.00      1
llama2-70b     99            Interactive  0.50      4
                             Offline      0.60      5
                             Server       0.60      5
               99.9          Interactive  0.50      4
                             Offline      0.60      5
                             Server       0.60      5
mixtral-8x7b   base          Offline      0.25      4
                             Server       0.75      4

Mismatches (18):
benchmark_base accuracy_tier    scenario           constraint predicted_top1 actual_top1
          gptj            99     Offline min_tput>=4724 tok/s       h100_sxm    h200_sxm
          gptj            99      Server min_tput>=4699 tok/s       h100_sxm    h200_sxm
    llama2-70b            99 Interactive     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b            99 Interactive     budget<=$3.99/hr         mi300x      mi325x
    llama2-70b            99     Offline     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b            99     Offline     budget<=$3.99/hr         mi300x      mi325x
    llama2-70b            99      Server     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b            99      Server     budget<=$3.99/hr         mi300x      mi325x
    llama2-70b          99.9 Interactive     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b          99.9 Interactive     budget<=$3.99/hr         mi300x      mi325x
    llama2-70b          99.9     Offline     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b          99.9     Offline     budget<=$3.99/hr         mi300x      mi325x
    llama2-70b          99.9      Server     budget<=$2.50/hr         mi300x      mi325x
    llama2-70b          99.9      Server     budget<=$3.99/hr         mi300x      mi325x
  mixtral-8x7b          base     Offline        unconstrained         mi300x      mi325x
  mixtral-8x7b          base     Offline     budget<=$2.50/hr         mi300x      mi325x
  mixtral-8x7b          base     Offline min_tput>=7158 tok/s         mi300x      mi325x
  mixtral-8x7b          base      Server min_tput>=6807 tok/s         mi300x      mi325x

## §7 · Interpretation

This is the first metric in the project that answers the question the recommender is
actually for — not "how close is the predicted number" but "does it point at the right GPU."
Because ground truth and predictions come from the same measured corpus (not new
benchmarking or hand-curated judgment calls), this result is reproducible from the data
already in this repository and holds up to exactly the same scrutiny as every other number
here — including the possibility that it fails, the same way the MAPE/ρ gates did.